name: Build Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev libxkbcommon-dev libwayland-dev libgtk-3-dev libudev-dev pkg-config

    - name: Build debug executable (Linux)
      run: cargo build --verbose # Removed --release

    - name: Archive Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: engine-linux
        path: engine/target/debug/engine # Changed path to debug

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build debug executable (Windows)
      run: cargo build --verbose # Removed --release

    - name: Archive Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: engine-windows
        path: engine/target/debug/engine.exe # Changed path to debug
