name: Build Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev libxkbcommon-dev libwayland-dev libgtk-3-dev libudev-dev pkg-config

    - name: Build release executable (Linux)
      # This 'env' block sets the RUSTFLAGS environment variable ONLY for this step.
      # It tells the Rust compiler to specifically allow dead_code, overriding the
      # CI environment's default of treating warnings as errors.
      env:
        RUSTFLAGS: "-A dead_code"
      run: cargo build --release --verbose

    - name: Archive Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: engine-linux
        path: engine/target/release/engine

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build release executable (Windows)
      # We apply the same fix here for the Windows build job.
      env:
        RUSTFLAGS: "-A dead_code"
      run: cargo build --release --verbose

    - name: Archive Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: engine-windows
        path: engine/target/release/engine.exe

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./engine
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Build release executable (macOS)
      env:
        RUSTFLAGS: "-A dead_code"
      run: cargo build --release --verbose

    - name: Archive macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: engine-macos
        path: engine/target/release/engine
